name: Send Image to TRMNL Server on a schedule

on:
  schedule:
    # api.met.no seems to update on 16. Let's do 10 mins after for buffer
    - cron: '26 * * * *'
  workflow_dispatch:  # adds a run button we can press

jobs:
  generate_and_post:
    name: python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - run: uv run main.py --user-agent "${{ github.server_url }}/${{ github.repository }}" --post-url "${{ secrets.TRMNL_WEBHOOK_POST_URL }}" --config config.yaml
